export const blogConfig = {
    medias: {
        Baidu: "https://baidu.com",
        BiliBili: "https://bilibili.com",
        // Bitbucket: "https://example.com",
        // Dingding: "https://example.com",
        // Discord: "https://example.com",
        // Dribbble: "https://example.com",
        // Email: "mailto:info@example.com",
        // Evernote: "https://example.com",
        // Facebook: "https://example.com",
        // Flipboard: "https://example.com",
        Gitee: "https://gitee.com",
        GitHub: "https://github.com",
        // Gitlab: "https://example.com",
        // Gmail: "mailto:info@example.com",
        // Instagram: "https://example.com",
        // Lark: "https://example.com",
        // Lines: "https://example.com",
        // Linkedin: "https://example.com",
        // Pinterest: "https://example.com",
        // Pocket: "https://example.com",
        // QQ: "https://example.com",
        // Qzone: "https://example.com",
        // Reddit: "https://example.com",
        // Rss: "https://example.com",
        // Steam: "https://example.com",
        // Twitter: "https://example.com",
        // Wechat: "https://example.com",
        // Weibo: "https://example.com",
        // Whatsapp: "https://example.com",
        // Youtube: "https://example.com",
        Zhihu: "https://zhihu.com",
        VuePressThemeHope: {
            icon: "https://theme-hope-assets.vuejs.press/logo.svg",
            link: "https://theme-hope.vuejs.press",
        },
    },
}
